Repository SEI-09-hip-hip-array/image-upload-client, pull requests merged in 2020-04, with the labels that each got.

#8 Added a navbar
  assets/scripts/app.js
  assets/scripts/auth/events.js
  assets/scripts/auth/ui.js
  assets/scripts/nav/events.js
  assets/styles/index.scss
  index.html
Labels: enhancement

#12 Added buttons to nav and app.js
  assets/scripts/app.js
  assets/styles/index.scss
  index.html
Labels: enhancement

#18 Added everything to readme
  README.md
Labels: documentation

#19 Visual Styling and requirements fixing
  README.md
  assets/scripts/app.js
  assets/scripts/auth/ui.js
  assets/scripts/templates/image-listing.handlebars
  assets/scripts/templates/image.handlebars
  assets/scripts/templates/update-form.handlebars
  assets/scripts/upload/api.js
  assets/scripts/upload/events.js
  assets/scripts/upload/ui.js
  assets/styles/index.scss
  index.html
Labels: Styling

#23 Show actions at inappropriate times
  assets/scripts/nav/events.js
  assets/scripts/templates/image-listing.handlebars
  assets/scripts/upload/api.js
  assets/scripts/upload/events.js
  assets/scripts/upload/ui.js
Labels: bug, enhancement

#24 Dev
  assets/scripts/nav/events.js
  assets/scripts/templates/image-listing.handlebars
  assets/scripts/upload/api.js
  assets/scripts/upload/events.js
  assets/scripts/upload/ui.js
Labels: bug
